//HintName: Solution.g.cs
// <auto-generated/>

using Fallout.Persistence.Solution.Model;
using Fallout.Solutions;
using Fallout.Common.IO;
using System.Runtime.CompilerServices;

internal class Solution(SolutionModel model, AbsolutePath path) : Fallout.Solutions.Solution(model, path)
{
    public Fallout.Solutions.Project _build => this.GetProject("_build");
    public Fallout.Solutions.Project Fallout_Build => this.GetProject("Fallout.Build");
    public Fallout.Solutions.Project Fallout_Build_Shared => this.GetProject("Fallout.Build.Shared");
    public Fallout.Solutions.Project Fallout_Build_Specs => this.GetProject("Fallout.Build.Specs");
    public Fallout.Solutions.Project Fallout_Cli => this.GetProject("Fallout.Cli");
    public Fallout.Solutions.Project Fallout_Cli_Specs => this.GetProject("Fallout.Cli.Specs");
    public Fallout.Solutions.Project Fallout_Common => this.GetProject("Fallout.Common");
    public Fallout.Solutions.Project Fallout_Common_Specs => this.GetProject("Fallout.Common.Specs");
    public Fallout.Solutions.Project Fallout_Components => this.GetProject("Fallout.Components");
    public Fallout.Solutions.Project Fallout_Consumer_Local => this.GetProject("Fallout.Consumer.Local");
    public Fallout.Solutions.Project Fallout_Consumer_NuGet => this.GetProject("Fallout.Consumer.NuGet");
    public Fallout.Solutions.Project Fallout_Core => this.GetProject("Fallout.Core");
    public Fallout.Solutions.Project Fallout_Core_Specs => this.GetProject("Fallout.Core.Specs");
    public Fallout.Solutions.Project Fallout_Migrate => this.GetProject("Fallout.Migrate");
    public Fallout.Solutions.Project Fallout_Migrate_Analyzers => this.GetProject("Fallout.Migrate.Analyzers");
    public Fallout.Solutions.Project Fallout_Migrate_Analyzers_Specs => this.GetProject("Fallout.Migrate.Analyzers.Specs");
    public Fallout.Solutions.Project Fallout_Migrate_Specs => this.GetProject("Fallout.Migrate.Specs");
    public Fallout.Solutions.Project Fallout_MSBuildTasks => this.GetProject("Fallout.MSBuildTasks");
    public Fallout.Solutions.Project Fallout_Persistence_Solution => this.GetProject("Fallout.Persistence.Solution");
    public Fallout.Solutions.Project Fallout_Persistence_Solution_Benchmarks => this.GetProject("Fallout.Persistence.Solution.Benchmarks");
    public Fallout.Solutions.Project Fallout_ProjectModel => this.GetProject("Fallout.ProjectModel");
    public Fallout.Solutions.Project Fallout_ProjectModel_Specs => this.GetProject("Fallout.ProjectModel.Specs");
    public Fallout.Solutions.Project Fallout_Solution => this.GetProject("Fallout.Solution");
    public Fallout.Solutions.Project Fallout_Solution_Specs => this.GetProject("Fallout.Solution.Specs");
    public Fallout.Solutions.Project Fallout_SourceGenerators => this.GetProject("Fallout.SourceGenerators");
    public Fallout.Solutions.Project Fallout_SourceGenerators_Specs => this.GetProject("Fallout.SourceGenerators.Specs");
    public Fallout.Solutions.Project Fallout_Tooling => this.GetProject("Fallout.Tooling");
    public Fallout.Solutions.Project Fallout_Tooling_Generator => this.GetProject("Fallout.Tooling.Generator");
    public Fallout.Solutions.Project Fallout_Tooling_Specs => this.GetProject("Fallout.Tooling.Specs");
    public Fallout.Solutions.Project Fallout_Utilities => this.GetProject("Fallout.Utilities");
    public Fallout.Solutions.Project Fallout_Utilities_IO_Compression => this.GetProject("Fallout.Utilities.IO.Compression");
    public Fallout.Solutions.Project Fallout_Utilities_IO_Globbing => this.GetProject("Fallout.Utilities.IO.Globbing");
    public Fallout.Solutions.Project Fallout_Utilities_Net => this.GetProject("Fallout.Utilities.Net");
    public Fallout.Solutions.Project Fallout_Utilities_Specs => this.GetProject("Fallout.Utilities.Specs");
    public Fallout.Solutions.Project Fallout_Utilities_Text_Json => this.GetProject("Fallout.Utilities.Text.Json");
    public Fallout.Solutions.Project Fallout_Utilities_Text_Yaml => this.GetProject("Fallout.Utilities.Text.Yaml");
    public Fallout.Solutions.Project Nuke_Build => this.GetProject("Nuke.Build");
    public Fallout.Solutions.Project Nuke_Common => this.GetProject("Nuke.Common");
    public Fallout.Solutions.Project Nuke_Common_Shim_Specs => this.GetProject("Nuke.Common.Shim.Specs");
    public Fallout.Solutions.Project Nuke_Components => this.GetProject("Nuke.Components");
    public Fallout.Solutions.Project Nuke_Components_Shim_Specs => this.GetProject("Nuke.Components.Shim.Specs");
    public Fallout.Solutions.Project Nuke_Consumer => this.GetProject("Nuke.Consumer");

    public _misc misc => Unsafe.As<_misc>(this.GetSolutionFolder("misc"));

    internal class _misc(SolutionFolderModel model, Fallout.Solutions.Solution solution) : Fallout.Solutions.SolutionFolder(model, solution)
    {
    
    
    }
}