//HintName: global__Fallout.Common.Regular.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public partial class Regular : global::Fallout.Common.Regular
    {
        public Regular(string a) : base(a) { }
        public Regular() { }
    }
}
