//HintName: global__Fallout.Common.IFoo.g.cs
// <auto-generated/>
// Generated by Fallout.SourceGenerators.TransitionShimGenerator.
// Mirrors a canonical Fallout.* type as a transition shim.

namespace Nuke.Common
{
    public partial interface IFoo : global::Fallout.Common.IFoo
    {
    }
}
