//HintName: ShimAllPublicTypesUnderAttribute.g.cs
// <auto-generated/>
#nullable enable
namespace Fallout.Migrate.Shims;

/// <summary>
/// Marks the consuming assembly as a transition-shim project. The
/// TransitionShimGenerator walks referenced Fallout.* assemblies and emits
/// shim types under <paramref name="toNamespacePrefix"/> mirroring the
/// public types whose namespace begins with <paramref name="fromNamespacePrefix"/>.
/// </summary>
[System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = true)]
internal sealed class ShimAllPublicTypesUnderAttribute : System.Attribute
{
    public ShimAllPublicTypesUnderAttribute(string fromNamespacePrefix, string toNamespacePrefix)
    {
        FromNamespacePrefix = fromNamespacePrefix;
        ToNamespacePrefix = toNamespacePrefix;
    }

    public string FromNamespacePrefix { get; }
    public string ToNamespacePrefix { get; }
}